### ISSUE TITLE
bring back navbar

### ISSUE THREAD

**Issue by Niclas1337** [UnbreakCode/Apple-Music-Web-Theme-for-Cider#3]
toggle for on/off?

**Comment by KillerParticles** [comment]
A toggle should be it, I prefer it off but some might prefer it on.

**Comment by Niclas1337** [comment]
bringing back the navbar and waiting for "theme options" in cider

**Comment by Niclas1337** [comment]
> bringing back the navbar and waiting for "theme options" in cider

bruh I'm coding a plugin to move it...
